version: "3.3"

services:
  push-notification-engine-backend:
    build:
      context: ../
      dockerfile: docker-deployment/java-dockerfile
    expose:
      - 8080
    network_mode: host

  nginx:
    build:
      context: .
      dockerfile: nginx-dockerfile
    expose:
      - 9000
    depends_on:
      - push-notification-engine-backend
    network_mode: host